[OnlineSubsystem]
DefaultPlatformService=EOS

[OnlineSubsystemEOS]
;Set to false to use Online Services EOS
bEnabled=false

[OnlineSubsystemEOSPlus]
bEnabled=false

[OnlineServices]
DefaultServices=Epic

[/Script/OnlineSubsystemEOS.EOSSettings]
CacheDir=CacheDir
TickBudgetInMilliseconds=0
bEnableOverlay=True
bEnableSocialOverlay=True
bEnableEditorOverlay=True
bUseEAS=True
bUseEOSConnect=True
bMirrorStatsToEOS=True
bMirrorAchievementsToEOS=True
bUseEOSSessions=True
bMirrorPresenceToEAS=True
bUseNewLoginFlow=true
!TitleStorageTags=ClearArray
+TitleStorageTags="OSS"
+TitleStorageTags="UI"
+TitleStorageTags="UI+OSS"
+TitleStorageTags="OSS+UI"
+TitleStorageTags="HOTFIX"
+TitleStorageTags="HOTFIX+UI"

;For OSSv2, fill in the following lines with actual details and then uncomment
[OnlineServices.EOS]
+ProductId=60f36fe9dfc14d6e9819418a5fd8dfca
+SandboxId=0a56487bec29495cac30e3cfe343c1bd
+DeploymentId=577e6707f5b647ada25def36961b0948
+ClientId=xyza7891wMlVGaDf2VVNwjiVRmjUneX0
+ClientSecret=C2J0Q/U7IxKYXLvyqxM1J2BS5q7WH5OprHezVPwrxtg

[/Script/Engine.OnlineEngineInterface]
;Added to enable OSSv2, "bUseOnlineServicesV2=true" is deprecated
ClassName=/Script/OnlineSubsystemUtils.OnlineServicesEngineInterfaceImpl

[/Script/SocketSubsystemEOS.NetDriverEOSBase]
bIsUsingP2PSockets=true

[/Script/Engine.Engine]
!NetDriverDefinitions=ClearArray
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="/Script/SocketSubsystemEOS.NetDriverEOSBase",DriverClassNameFallback="/Script/OnlineSubsystemUtils.IpNetDriver")
+NetDriverDefinitions=(DefName="BeaconNetDriver",DriverClassName="/Script/SocketSubsystemEOS.NetDriverEOSBase",DriverClassNameFallback="/Script/OnlineSubsystemUtils.IpNetDriver")
+NetDriverDefinitions=(DefName="DemoNetDriver",DriverClassName="/Script/Engine.DemoNetDriver",DriverClassNameFallback="/Script/Engine.DemoNetDriver")

[OnlineServices.Lobbies]
+SchemaDescriptors=(Id="GameLobby", ParentId="LobbyBase")
!SchemaCategoryAttributeDescriptors=ClearArray
+SchemaCategoryAttributeDescriptors=(SchemaId="LobbyBase", CategoryId="Lobby", AttributeIds=("SchemaCompatibilityId", "PRESENCESEARCH", "OSSv2"))
+SchemaCategoryAttributeDescriptors=(SchemaId="LobbyBase", CategoryId="LobbyMember")
+SchemaCategoryAttributeDescriptors=(SchemaId="GameLobby", CategoryId="Lobby", AttributeIds=("GAMEMODE", "MAPNAME", "MATCHTIMEOUT", "SESSIONTEMPLATENAME"))
+SchemaCategoryAttributeDescriptors=(SchemaId="GameLobby", CategoryId="LobbyMember", AttributeIds=("GAMEMODE"))
+SchemaAttributeDescriptors=(Id="SchemaCompatibilityId", Type="Int64", Flags=("Public", "SchemaCompatibilityId"))
+SchemaAttributeDescriptors=(Id="PRESENCESEARCH", Type="Bool", Flags=("Public", "Searchable"))
+SchemaAttributeDescriptors=(Id="GAMEMODE", Type="String", Flags=("Public"), MaxSize=64)
+SchemaAttributeDescriptors=(Id="MAPNAME", Type="String", Flags=("Public"), MaxSize=64)
+SchemaAttributeDescriptors=(Id="MATCHTIMEOUT", Type="Double", Flags=("Public"))
+SchemaAttributeDescriptors=(Id="SESSIONTEMPLATENAME", Type="String", Flags=("Public"), MaxSize=64)
+SchemaAttributeDescriptors=(Id="OSSv2", Type="Bool", Flags=("Public"))

[/Script/CommonUser.CommonUserBasicPresence]
bEnableSessionsBasedPresence=true
PresenceStatusInGame=Status_InGame
PresenceStatusMainMenu=Status_MainMenu
PresenceStatusMatchmaking=Status_Matchmaking
PresenceKeyGameMode=game_mode
PresenceKeyMapName=map_name